services:
  - type: web
    name: bami-backend
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: OPENAI_API_KEY
        sync: false
      - key: BAMI_API_KEY
        sync: false
      - key: CORS_ORIGIN
        value: "*"
